name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Assemble with Gradle
      run: ./gradlew assemble
    - name: Save apk artifact
      uses: actions/upload-artifact@master
      with:
        name: trapta-app-unsigned
        path: ${{ github.workspace }}/app/build/outputs/apk/release/app-release-unsigned.apk


  release:
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    needs: [build]
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          New Trapta App version
        draft: true
        prerelease: false

    
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3

    - name: Upload unsigned Apk
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: trapta-app-unsigned/app-release-unsigned.apk
        asset_name: trapta-app-unsigned.apk
        asset_content_type: application/zip
